# Generated by Django 5.1.2 on 2024-10-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.SmallIntegerField(max_length=12)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
    ]
